In [21]:
import torch
from d2l import torch as d2l

In [22]:
def corr2d_multi_in(X,K): #X与K的第一维是相同的，保证每个通道与每个卷积层进行互相关运算
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))
X=torch.tensor([[[1.0,2,3],[1.0,2,3]],[[0.0,1,2],[0.0,1,2]],[[1.0,1,2],[1.0,1,2]]])
print(X.shape)
K=torch.tensor([[[1.0,2]],[[1.0,2]],[[1.0,2]]])
print(K.shape)
corr2d_multi_in(X,K)

torch.Size([3, 2, 3])
torch.Size([3, 1, 2])


tensor([[10., 18.],
        [10., 18.]])

In [23]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],0)
K=torch.stack([K,K+1,K+2],0) #这个块不要运行很多次,不然会一直堆叠
K.shape

torch.Size([3, 3, 1, 2])

In [24]:
corr2d_multi_in_out(X,K)

tensor([[[10., 18.],
         [10., 18.]],

        [[16., 29.],
         [16., 29.]],

        [[22., 40.],
         [22., 40.]]])

In [25]:
#验证1x1的卷积就是全联结层
X=torch.normal(0,1,(3,3,3))
print(X)
c_i,h,w=X.shape
print(X.reshape(c_i,h*w))

tensor([[[-0.6296, -1.7107,  1.5552],
         [-1.5386,  0.4742,  0.6948],
         [ 0.0641, -0.2322, -0.3134]],

        [[ 0.2133,  0.6777,  0.2232],
         [ 0.2552,  0.9463,  0.8310],
         [ 2.0563,  1.7197, -1.8478]],

        [[-0.9885, -0.5534,  1.8458],
         [ 0.1838, -0.5593,  1.5993],
         [-0.1336, -2.0184, -0.1777]]])
tensor([[-0.6296, -1.7107,  1.5552, -1.5386,  0.4742,  0.6948,  0.0641, -0.2322,
         -0.3134],
        [ 0.2133,  0.6777,  0.2232,  0.2552,  0.9463,  0.8310,  2.0563,  1.7197,
         -1.8478],
        [-0.9885, -0.5534,  1.8458,  0.1838, -0.5593,  1.5993, -0.1336, -2.0184,
         -0.1777]])


In [28]:
def corr2d_multi_in_out1x1(X,K): #这个函数将1x1卷积转化成全连接层的形式
    c_i,h,w=X.shape
    c_o=K.shape[0]
    X=X.reshape(c_i,h*w)
    K=K.reshape(c_o,c_i)
    Y=torch.matmul(K,X)
    return Y.reshape(c_o,h,w)
X=torch.normal(0,1,(3,3,3))
K=torch.normal(0,1,(2,3,1,1))
Y1=corr2d_multi_in_out(X,K)
Y2=corr2d_multi_in_out1x1(X,K)

In [29]:
Y1==Y2

tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])