In [22]:
import os
import pandas as pd
import torch
import numpy as np

In [8]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("3,NA,134500\n")
    f.write("NA,NA,123900\n")
data=pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       3.0   NaN  134500
3       NaN   NaN  123900


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       3.0   NaN  134500
3       NaN   NaN  123900

In [15]:
#处理缺失数据
input,output=data.iloc[:,0:2],data.iloc[:,2]
print(input)
print(output)
input=input.fillna(input.mean(numeric_only=True)) #缺失值变成均值
print(input)
input=pd.get_dummies(input,dummy_na=True)
print(input)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       3.0   NaN
3       NaN   NaN
0    127500
1    106000
2    134500
3    123900
Name: Price, dtype: int64
   NumRooms Alley
0       2.5  Pave
1       2.0   NaN
2       3.0   NaN
3       2.5   NaN
   NumRooms  Alley_Pave  Alley_nan
0       2.5        True      False
1       2.0       False       True
2       3.0       False       True
3       2.5       False       True


In [29]:
print(input.values)
X,y=torch.tensor(input.values.astype(np.float32)),torch.tensor(output.values)
print(X)
print(y)

[[2.5 True False]
 [2.0 False True]
 [3.0 False True]
 [2.5 False True]]
tensor([[2.5000, 1.0000, 0.0000],
        [2.0000, 0.0000, 1.0000],
        [3.0000, 0.0000, 1.0000],
        [2.5000, 0.0000, 1.0000]])
tensor([127500, 106000, 134500, 123900])


In [34]:
a=torch.arange(20).reshape(4,5)
a,a.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

In [35]:
a=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
a==a.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [37]:
#求L2范数
a=torch.tensor([1.0,2,3])
torch.norm(a)

tensor(3.7417)