In [1]:
import torch
import torch.nn as nn
from d2l import torch as d2l

In [2]:
def pool2d(X,pool_size,mode='max'):
    p_h,p_w=pool_size
    Y=torch.zeros(X.shape[0]-p_h+1,X.shape[1]-p_w+1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            if mode=='avg':
                Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
    return Y

In [5]:
X=torch.tensor([[1.0,2,3],[0,1,2],[3,4,5]])
print(pool2d(X,(2,2)))
print(pool2d(X,(2,2),'avg'))

tensor([[2., 3.],
        [4., 5.]])
tensor([[1., 2.],
        [2., 3.]])


In [6]:
X=torch.arange(16,dtype=torch.float32).reshape(1,1,4,4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [8]:
pool2d1=nn.MaxPool2d(3) #最大池化层的长宽都是3，默认步幅是kernel大小
pool2d1(X)

tensor([[[[10.]]]])

In [9]:
#也可以自定义步幅
pool2d2=nn.MaxPool2d(kernel_size=3,stride=1)
pool2d2(X)

tensor([[[[10., 11.],
          [14., 15.]]]])

In [10]:
#也可以指定padding
pool2d3=nn.MaxPool2d(kernel_size=3,padding=1,stride=1)
pool2d3(X)

tensor([[[[ 5.,  6.,  7.,  7.],
          [ 9., 10., 11., 11.],
          [13., 14., 15., 15.],
          [13., 14., 15., 15.]]]])